version: '2.1'

services:
  horse:
    image: hashload/delphi-dev:10.3.2-rio
    privileged: true
    tty: true
    ports:
      - '9000:9000'
      - '64211:64211'    

  mongo:
    image: mongo
    ports:
      - '27017:27017'